baseURL = "https://example.com"
languageCode = "en-us"
title = "Amaral"
theme="Amaral"
copyright = "© Amaral"
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
[params]
	mode="auto"
	useCDN=false
	subtitle = "Mathematical Software Engineer"

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/amaralpedr"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/amrlpdr"

[[params.social]]
name = "GitLab"
icon = "gitlab"
url = "https://github.com/amaralpedr"
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4
